"use strict";
exports.__esModule = true;
var Cat_1 = require("./Cat");
var Dog_1 = require("./Dog");
var Animal_1 = require("./Animal");
var Mammal_1 = require("./Mammal");
var a = new Cat_1.Cat("Habitat1", "Family1", "Cat1", "MEOW1");
var b = new Cat_1.Cat("Habitat2", "Family4", "Cat2", "MEOW2");
var c = new Cat_1.Cat("Habitat3", "Family3", "Cat3", "MEOW3");
var d = new Cat_1.Cat("Habitat4", "Family2", "Cat4", "MEOW4");
a.talk();
b.show();
console.log("-------------------------------------------------------------");
var e = new Dog_1.Dog("Habitat1", "Race1", "Dog1", "BARK1");
var f = new Dog_1.Dog("Habitat2", "Race2", "Dog2", "BARK2");
var g = new Dog_1.Dog("Habitat3", "Race3", "Dog3", "BARk3");
f.talk();
g.show();
console.log("There Are " + Animal_1.Animal.nAnimals + " Animals");
console.log("There Are " + Mammal_1.Mammal.nMammals + " Mammals");
