# Generated by Django 3.1.7 on 2021-04-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('discount', models.FloatField(null=True)),
                ('description', models.CharField(max_length=300)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
