# Generated by Django 3.1.7 on 2021-04-12 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('price', models.FloatField(null=True)),
                ('description', models.CharField(max_length=300)),
                ('ranking', models.IntegerField()),
                ('image', models.ImageField(upload_to='static/images')),
                ('quantity', models.IntegerField()),
                ('stock', models.BooleanField()),
                ('brand', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Smartphones', 'Smartphones'), ('Computers', 'Computers'), ('Tablets', 'Tablets'), ('Drones', 'Drones'), ('Televisions', 'Televisions')], max_length=150)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.promotion')),
            ],
        ),
    ]
