# Generated by Django 3.1.7 on 2021-04-13 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ranking',
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.promotion'),
        ),
    ]
