# Generated by Django 3.1.7 on 2021-04-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_payment_paymentmethod_shoppingcart_shoppingcartitem'),
        ('app', '0003_auto_20210413_1516'),
    ]

    operations = [
    ]
