# Generated by Django 3.1.7 on 2021-04-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210414_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=80)),
                ('userEmail', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=400)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
