# Generated by Django 3.1.7 on 2021-04-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
