# Generated by Django 3.1.7 on 2021-04-22 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210417_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 22, 21, 57, 18, 982360, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
