# Generated by Django 3.2 on 2021-04-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210423_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user_id',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
