# Generated by Django 3.2 on 2021-04-23 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_shoppingcart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcartitem',
            old_name='item_id',
            new_name='product',
        ),
    ]
