# Generated by Django 3.1.7 on 2021-04-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_comment_product'),
        ('app', '0014_auto_20210424_1455'),
    ]

    operations = [
    ]
