# Generated by Django 3.1.7 on 2021-04-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_merge_20210424_1710'),
        ('app', '0016_alter_product_image'),
    ]

    operations = [
    ]
