# Generated by Django 3.2 on 2021-04-26 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210426_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('buyer', models.CharField(max_length=150)),
                ('date', models.DateField(default=datetime.datetime(2021, 4, 26, 11, 16, 37, 429462))),
                ('total', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='UserCredits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sold',
        ),
        migrations.AddField(
            model_name='payment',
            name='usedCredits',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 11, 16, 37, 429462)),
        ),
        migrations.AddField(
            model_name='sold',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='sold',
            name='promotion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.promotion'),
        ),
    ]
