# Generated by Django 3.2 on 2021-04-26 10:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210426_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 11, 21, 10, 785001)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 11, 21, 10, 784000)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='promotion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.promotion'),
        ),
    ]
