# Generated by Django 3.2 on 2021-04-26 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210426_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='username',
            field=models.CharField(default='TechOn', max_length=250),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentDate',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 11, 45, 24, 701325)),
        ),
        migrations.AlterField(
            model_name='sold',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 4, 26, 11, 45, 24, 701325)),
        ),
    ]
